### ISSUE TITLE
enum SendFileError

### ISSUE THREAD

**Issue by Davarg** [webim/webim-client-sdk-ios-wrapper#1]
enum SendFileError doesn't contain anymore UPLOADED_FILE_NOT_FOUND , UNKNOWN
Original WebimClientLibrary -> 3.14.2

**Comment by webim** [comment]
Enum SendFileError contains UPLOADED_FILE_NOT_FOUND , UNKNOWN since Original WebimClientLibrary -> 3.17.0.
